#cloud-config

packages:
  - docker.io
  - git

# create the docker group
groups:
  - docker

users:
  - name: cloudinit
    groups: docker
    home: /home/cloudinit
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  - sudo docker login --username sidwar --password-stdin Password@123
  - sudo docker pull sidwar/node-bulletin-app
  - sudo docker run  -e "MY_VAR=myValue" docker pull sidwar/node-bulletin-app
  - sudo docker run -d -p 80:80 -e SOME_VAR="SOME VALUE" sidwar/node-bulletin-app 